/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    team: Team;
    posts: Post;
    categories: Category;
    enquiries: Enquiry;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
    'site-status': SiteStatus;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'site-status': SiteStatusSelect<false> | SiteStatusSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the website. Edit the wording, photos and SEO, then Save. Changes appear on the live site after you click Publish website on the dashboard.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  h1?: string | null;
  eyebrow?: string | null;
  h2?: string | null;
  h3?: string | null;
  /**
   * Shown bold beside the photo.
   */
  hook?: string | null;
  image?: {
    /**
     * Choose or upload a photo. Leave empty to keep the photo currently built into the site.
     */
    upload?: (number | null) | Media;
    /**
     * The photo shipped with the site, used when no library photo is chosen. Changed by the developer only.
     */
    path?: string | null;
    /**
     * Describes the photo for search engines and screen readers.
     */
    alt?: string | null;
  };
  /**
   * Paragraphs, bullet lists, sub-headings and tables. Click a row to open it; drag the handle on the left to reorder.
   */
  body?:
    | {
        type: 'p' | 'ul' | 'h4' | 'table';
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        text?: string | null;
        items?:
          | {
              /**
               * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
               */
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * One table row per line. Separate the cells in a row with a vertical bar |. The first line is the header row.
         */
        rowsText?: string | null;
        /**
         * Leave blank to always show.
         */
        mode?: ('pre-opening' | 'open' | 'booking') | null;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        id?: string | null;
      }[]
    | null;
  ctaBand?: string | null;
  /**
   * Each section is a heading with its own content. Click a section to open it; drag the handle to reorder.
   */
  details?:
    | {
        heading: string;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        /**
         * Paragraphs, bullet lists, sub-headings and tables. Click a row to open it; drag the handle on the left to reorder.
         */
        nodes?:
          | {
              type: 'p' | 'ul' | 'h4' | 'table';
              /**
               * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
               */
              text?: string | null;
              items?:
                | {
                    /**
                     * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
                     */
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * One table row per line. Separate the cells in a row with a vertical bar |. The first line is the header row.
               */
              rowsText?: string | null;
              /**
               * Leave blank to always show.
               */
              mode?: ('pre-opening' | 'open' | 'booking') | null;
              /**
               * Leave blank to always show. Feature switches live in Site Settings.
               */
              gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  closingCta?: string | null;
  gatedText?: {
    /**
     * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
     */
    hook?: string | null;
    /**
     * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
     */
    bodyIntro?: string | null;
  };
  intro?:
    | {
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Each section is a heading with its own content. Click a section to open it; drag the handle to reorder.
   */
  sections?:
    | {
        heading: string;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        /**
         * Paragraphs, bullet lists, sub-headings and tables. Click a row to open it; drag the handle on the left to reorder.
         */
        nodes?:
          | {
              type: 'p' | 'ul' | 'h4' | 'table';
              /**
               * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
               */
              text?: string | null;
              items?:
                | {
                    /**
                     * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
                     */
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * One table row per line. Separate the cells in a row with a vertical bar |. The first line is the header row.
               */
              rowsText?: string | null;
              /**
               * Leave blank to always show.
               */
              mode?: ('pre-opening' | 'open' | 'booking') | null;
              /**
               * Leave blank to always show. Feature switches live in Site Settings.
               */
              gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The rotating banner at the top of the home page. First slide shows first.
   */
  slides?:
    | {
        headline: string;
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        sub?: string | null;
        linkText?: string | null;
        /**
         * A page such as /kids-gap-free-dentistry-cronulla/ or {{cta}} for the booking button.
         */
        linkHref?: string | null;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        id?: string | null;
      }[]
    | null;
  heroImage?: {
    /**
     * Choose or upload a photo. Leave empty to keep the photo currently built into the site.
     */
    upload?: (number | null) | Media;
    /**
     * The photo shipped with the site, used when no library photo is chosen. Changed by the developer only.
     */
    path?: string | null;
    /**
     * Describes the photo for search engines and screen readers.
     */
    alt?: string | null;
  };
  providers?:
    | {
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  pillars?:
    | {
        title: string;
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        text?: string | null;
        /**
         * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
         */
        href?: string | null;
        /**
         * Developer setting: an icon name from components/Icons.tsx.
         */
        icon?: string | null;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        fallback?: {
          title?: string | null;
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          text?: string | null;
          /**
           * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
           */
          href?: string | null;
          /**
           * Developer setting: an icon name from components/Icons.tsx.
           */
          icon?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  welcome?: {
    h2?: string | null;
    h3?: string | null;
    paragraphs?:
      | {
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  welcomeImage?: {
    /**
     * Choose or upload a photo. Leave empty to keep the photo currently built into the site.
     */
    upload?: (number | null) | Media;
    /**
     * The photo shipped with the site, used when no library photo is chosen. Changed by the developer only.
     */
    path?: string | null;
    /**
     * Describes the photo for search engines and screen readers.
     */
    alt?: string | null;
  };
  categoryCards?:
    | {
        title: string;
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        text?: string | null;
        /**
         * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
         */
        href?: string | null;
        /**
         * Developer setting: an icon name from components/Icons.tsx.
         */
        icon?: string | null;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        fallback?: {
          title?: string | null;
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          text?: string | null;
          /**
           * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
           */
          href?: string | null;
          /**
           * Developer setting: an icon name from components/Icons.tsx.
           */
          icon?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  treatments?: {
    h2?: string | null;
    h3?: string | null;
    tiles?:
      | {
          title: string;
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          text?: string | null;
          /**
           * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
           */
          href?: string | null;
          image?: {
            /**
             * Choose or upload a photo. Leave empty to keep the photo currently built into the site.
             */
            upload?: (number | null) | Media;
            /**
             * The photo shipped with the site, used when no library photo is chosen. Changed by the developer only.
             */
            path?: string | null;
            /**
             * Describes the photo for search engines and screen readers.
             */
            alt?: string | null;
          };
          /**
           * Leave blank to always show. Feature switches live in Site Settings.
           */
          gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
          id?: string | null;
        }[]
      | null;
  };
  iconBlocks?:
    | {
        title: string;
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        text?: string | null;
        /**
         * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
         */
        href?: string | null;
        /**
         * Developer setting: an icon name from components/Icons.tsx.
         */
        icon?: string | null;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        fallback?: {
          title?: string | null;
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          text?: string | null;
          /**
           * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
           */
          href?: string | null;
          /**
           * Developer setting: an icon name from components/Icons.tsx.
           */
          icon?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  paymentBand?: {
    h2?: string | null;
    lines?:
      | {
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    logo?: string | null;
  };
  note?: {
    h2?: string | null;
    h3?: string | null;
    paragraphs?:
      | {
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    signoff?: string | null;
  };
  dentistsImage?: {
    /**
     * Choose or upload a photo. Leave empty to keep the photo currently built into the site.
     */
    upload?: (number | null) | Media;
    /**
     * The photo shipped with the site, used when no library photo is chosen. Changed by the developer only.
     */
    path?: string | null;
    /**
     * Describes the photo for search engines and screen readers.
     */
    alt?: string | null;
  };
  introLine?: string | null;
  serviceList?:
    | {
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  closingLine?: string | null;
  featured?:
    | {
        title: string;
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        text?: string | null;
        /**
         * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
         */
        href?: string | null;
        image?: {
          /**
           * Choose or upload a photo. Leave empty to keep the photo currently built into the site.
           */
          upload?: (number | null) | Media;
          /**
           * The photo shipped with the site, used when no library photo is chosen. Changed by the developer only.
           */
          path?: string | null;
          /**
           * Describes the photo for search engines and screen readers.
           */
          alt?: string | null;
        };
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        fallback?: {
          title?: string | null;
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          text?: string | null;
          /**
           * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
           */
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  blurbs?:
    | {
        title: string;
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        text?: string | null;
        /**
         * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
         */
        href?: string | null;
        /**
         * Developer setting: an icon name from components/Icons.tsx.
         */
        icon?: string | null;
        /**
         * Leave blank to always show. Feature switches live in Site Settings.
         */
        gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
        fallback?: {
          title?: string | null;
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          text?: string | null;
          /**
           * A page on this site such as /general-dentistry-cronulla/ or a full https:// address.
           */
          href?: string | null;
          /**
           * Developer setting: an icon name from components/Icons.tsx.
           */
          icon?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  closing?: {
    h2?: string | null;
    paragraphs?:
      | {
          /**
           * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
           */
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
     */
    closingLine?: string | null;
  };
  /**
   * Shown in the browser tab and in Google. Keep under about 60 characters.
   */
  metaTitle: string;
  /**
   * The summary Google shows under the title. Aim for 120 to 155 characters.
   */
  metaDescription: string;
  /**
   * Shown when this page is shared on Facebook or in messages. 1200 x 630 works best. Leave empty to use the default share image.
   */
  ogImage?: (number | null) | Media;
  noindex?: boolean | null;
  /**
   * Only if this page should point search engines at a different address. Leave empty to use its own.
   */
  canonical?: string | null;
  /**
   * For the SEO team. Not shown on the page.
   */
  primaryKeyword?: string | null;
  metaTitleGated?: string | null;
  metaDescriptionGated?: string | null;
  /**
   * Which template renders this page. Developer setting.
   */
  kind: 'service' | 'prose' | 'home' | 'hub' | 'contact';
  /**
   * Web address of the page, for example general-dentistry-cronulla. Changing it changes the URL, so add a redirect from the old one.
   */
  slug: string;
  /**
   * The full path, for example /general-dentistry-cronulla/. Filled in from the slug when empty.
   */
  route: string;
  breadcrumb?:
    | {
        /**
         * Plain text with a few shortcuts: **bold**, {{phone}} for the practice phone, {{email}} for the email, and [link text](/route/) for a link.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  category?: ('general' | 'children' | 'cosmetic' | 'restorative' | 'gum' | 'other') | null;
  /**
   * Leave blank to always show. Feature switches live in Site Settings.
   */
  gate?: ('emergency' | 'cdbs' | 'zipAfterpay') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload photos here, then choose them on a page. Keep alt text short and descriptive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What is in the photo, in a few words. Used by search engines and screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The dentists shown on the About page. The bios themselves are edited on the About page (Meet the team section).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * For example Dr Ram Nathwani
   */
  fullName: string;
  /**
   * How the copy refers to them, for example Dr Ram. Used to match the bio on the About page.
   */
  shortName: string;
  givenName: string;
  familyName: string;
  /**
   * For example Principal Dentist
   */
  title: string;
  photo?: (number | null) | Media;
  /**
   * Shown on the About page. Leave a blank line between paragraphs. Supports **bold**.
   */
  bio?: string | null;
  /**
   * Keeps the record but removes them from the About page and search listings.
   */
  hidden?: boolean | null;
  photoPath?: string | null;
  order?: number | null;
  /**
   * Internal key, for example ram.
   */
  key?: string | null;
  alumniOf?: string | null;
  credentials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  knowsAbout?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Added to the Person schema when set.
   */
  sameAs?: string | null;
  /**
   * From the AHPRA public register. Optional; shown in schema only when set.
   */
  ahpra?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles appear at /blog/ once published and the website is republished. Keep to general dental information; no reviews or claims about results.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two sentences shown on the blog index and used as the meta description when the SEO one is empty.
   */
  excerpt: string;
  featuredImage?: (number | null) | Media;
  /**
   * Written with the editor on the /admin dashboard. Edit there rather than here.
   */
  body: string;
  author?: string | null;
  categories?: (number | Category)[] | null;
  /**
   * Shown on the article. Defaults to today when published.
   */
  publishedAt?: string | null;
  /**
   * Defaults to the article title plus the practice name.
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Defaults to the featured image.
   */
  ogImage?: (number | null) | Media;
  noindex?: boolean | null;
  /**
   * Web address under /blog/. Filled in from the title when empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Filled in from the title when empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages from the website contact form. Each one is also emailed to reception and SmileOx.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  form: 'contact' | 'eoi';
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  source?: string | null;
  /**
   * Whether the notification email went out.
   */
  emailStatus?: ('sent' | 'failed' | 'skipped') | null;
  emailError?: string | null;
  followedUp?: boolean | null;
  notes?: string | null;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old address to a new one. Takes effect after the website is republished.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old path on this site, for example /old-page/
   */
  from: string;
  /**
   * Where to send visitors: a path such as /services/ or a full https:// address.
   */
  to: string;
  type?: ('301' | '302') | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can log in. Editors change content; admins (GYA) also manage users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  h1?: T;
  eyebrow?: T;
  h2?: T;
  h3?: T;
  hook?: T;
  image?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  body?:
    | T
    | {
        type?: T;
        text?: T;
        items?:
          | T
          | {
              value?: T;
              id?: T;
            };
        rowsText?: T;
        mode?: T;
        gate?: T;
        id?: T;
      };
  ctaBand?: T;
  details?:
    | T
    | {
        heading?: T;
        gate?: T;
        nodes?:
          | T
          | {
              type?: T;
              text?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              rowsText?: T;
              mode?: T;
              gate?: T;
              id?: T;
            };
        id?: T;
      };
  closingCta?: T;
  gatedText?:
    | T
    | {
        hook?: T;
        bodyIntro?: T;
      };
  intro?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        gate?: T;
        nodes?:
          | T
          | {
              type?: T;
              text?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              rowsText?: T;
              mode?: T;
              gate?: T;
              id?: T;
            };
        id?: T;
      };
  slides?:
    | T
    | {
        headline?: T;
        sub?: T;
        linkText?: T;
        linkHref?: T;
        gate?: T;
        id?: T;
      };
  heroImage?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  providers?:
    | T
    | {
        value?: T;
        id?: T;
      };
  pillars?:
    | T
    | {
        title?: T;
        text?: T;
        href?: T;
        icon?: T;
        gate?: T;
        fallback?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              icon?: T;
            };
        id?: T;
      };
  welcome?:
    | T
    | {
        h2?: T;
        h3?: T;
        paragraphs?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  welcomeImage?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  categoryCards?:
    | T
    | {
        title?: T;
        text?: T;
        href?: T;
        icon?: T;
        gate?: T;
        fallback?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              icon?: T;
            };
        id?: T;
      };
  treatments?:
    | T
    | {
        h2?: T;
        h3?: T;
        tiles?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              image?:
                | T
                | {
                    upload?: T;
                    path?: T;
                    alt?: T;
                  };
              gate?: T;
              id?: T;
            };
      };
  iconBlocks?:
    | T
    | {
        title?: T;
        text?: T;
        href?: T;
        icon?: T;
        gate?: T;
        fallback?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              icon?: T;
            };
        id?: T;
      };
  paymentBand?:
    | T
    | {
        h2?: T;
        lines?:
          | T
          | {
              value?: T;
              id?: T;
            };
        logo?: T;
      };
  note?:
    | T
    | {
        h2?: T;
        h3?: T;
        paragraphs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        signoff?: T;
      };
  dentistsImage?:
    | T
    | {
        upload?: T;
        path?: T;
        alt?: T;
      };
  introLine?: T;
  serviceList?:
    | T
    | {
        value?: T;
        id?: T;
      };
  closingLine?: T;
  featured?:
    | T
    | {
        title?: T;
        text?: T;
        href?: T;
        image?:
          | T
          | {
              upload?: T;
              path?: T;
              alt?: T;
            };
        gate?: T;
        fallback?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
            };
        id?: T;
      };
  blurbs?:
    | T
    | {
        title?: T;
        text?: T;
        href?: T;
        icon?: T;
        gate?: T;
        fallback?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
              icon?: T;
            };
        id?: T;
      };
  closing?:
    | T
    | {
        h2?: T;
        paragraphs?:
          | T
          | {
              value?: T;
              id?: T;
            };
        closingLine?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  canonical?: T;
  primaryKeyword?: T;
  metaTitleGated?: T;
  metaDescriptionGated?: T;
  kind?: T;
  slug?: T;
  route?: T;
  breadcrumb?:
    | T
    | {
        value?: T;
        id?: T;
      };
  category?: T;
  gate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  fullName?: T;
  shortName?: T;
  givenName?: T;
  familyName?: T;
  title?: T;
  photo?: T;
  bio?: T;
  hidden?: T;
  photoPath?: T;
  order?: T;
  key?: T;
  alumniOf?: T;
  credentials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  knowsAbout?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sameAs?: T;
  ahpra?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  body?: T;
  author?: T;
  categories?: T;
  publishedAt?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  form?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  source?: T;
  emailStatus?: T;
  emailError?: T;
  followedUp?: T;
  notes?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Practice details used across the whole website. Save, then Publish website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  /**
   * For example (02) 8599 9815
   */
  phone: string;
  /**
   * International format, no spaces: +61285999815
   */
  phoneE164: string;
  email: string;
  address: {
    street: string;
    suburb: string;
    state: string;
    postcode: string;
  };
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  gbpShareUrl?: string | null;
  /**
   * Leave empty to keep the logo built into the site.
   */
  logo?: (number | null) | Media;
  /**
   * Leave empty to keep the colours the site was designed with.
   */
  colours?: {
    navy?: string | null;
    cyan?: string | null;
  };
  /**
   * One row per day, Monday to Sunday. Tick Closed for days the practice is shut.
   */
  hours?:
    | {
        day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
        closed?: boolean | null;
        open?: string | null;
        close?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  hooks?: {
    /**
     * For example: Open until 7pm Mondays
     */
    lateMonday?: string | null;
    /**
     * For example: Early appointments from 7am Fridays
     */
    earlyFriday?: string | null;
  };
  mode: 'pre-opening' | 'open';
  /**
   * For example: late November 2026, or 16 November 2026
   */
  openingDateLabel?: string | null;
  openingDate?: string | null;
  /**
   * ISO date-time. Leave empty to hide the countdown.
   */
  openingDateTime?: string | null;
  /**
   * Core Practice booking page. Every Book online button uses this.
   */
  bookingUrl?: string | null;
  bookingChooser?: boolean | null;
  /**
   * Shown in the Book online pop-up, in this order. Leave the link blank on Cronulla to use the online booking link above.
   */
  bookingLocations?:
    | {
        name: string;
        address?: string | null;
        url?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the home page and finances pages, for example: nib preferred provider
   */
  payment?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Turning one off hides every page, section and line that depends on it.
   */
  features?: {
    emergency?: boolean | null;
    cdbs?: boolean | null;
    zipAfterpay?: boolean | null;
  };
  teamNamesConfirmed?: boolean | null;
  parkingNotes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * For example: 1 November 2026. Empty hides the line.
   */
  privacyLastUpdated?: string | null;
  ga4Id?: string | null;
  /**
   * Leave blank unless a container is set up.
   */
  gtmId?: string | null;
  /**
   * Numbers only. Leave blank to not load the pixel.
   */
  metaPixelId?: string | null;
  sameAs?: {
    facebook?: string | null;
    instagram?: string | null;
  };
  sister?: {
    name?: string | null;
    url?: string | null;
    /**
     * For example: 50 years in the Shire
     */
    heritage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Fallbacks used when a page has no share image of its own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * 1200 x 630. Leave empty to keep the share card built from the logo.
   */
  ogImage?: (number | null) | Media;
  /**
   * Used only for pages without their own.
   */
  defaultDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-status".
 */
export interface SiteStatus {
  id: number;
  lastChangedAt?: string | null;
  lastPublishedAt?: string | null;
  lastPublishedBy?: string | null;
  lastPublishStatus?: string | null;
  lastImportAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  phoneE164?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        suburb?: T;
        state?: T;
        postcode?: T;
      };
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  gbpShareUrl?: T;
  logo?: T;
  colours?:
    | T
    | {
        navy?: T;
        cyan?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        closed?: T;
        open?: T;
        close?: T;
        label?: T;
        id?: T;
      };
  hooks?:
    | T
    | {
        lateMonday?: T;
        earlyFriday?: T;
      };
  mode?: T;
  openingDateLabel?: T;
  openingDate?: T;
  openingDateTime?: T;
  bookingUrl?: T;
  bookingChooser?: T;
  bookingLocations?:
    | T
    | {
        name?: T;
        address?: T;
        url?: T;
        note?: T;
        id?: T;
      };
  payment?:
    | T
    | {
        value?: T;
        id?: T;
      };
  features?:
    | T
    | {
        emergency?: T;
        cdbs?: T;
        zipAfterpay?: T;
      };
  teamNamesConfirmed?: T;
  parkingNotes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  privacyLastUpdated?: T;
  ga4Id?: T;
  gtmId?: T;
  metaPixelId?: T;
  sameAs?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  sister?:
    | T
    | {
        name?: T;
        url?: T;
        heritage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  ogImage?: T;
  defaultDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-status_select".
 */
export interface SiteStatusSelect<T extends boolean = true> {
  lastChangedAt?: T;
  lastPublishedAt?: T;
  lastPublishedBy?: T;
  lastPublishStatus?: T;
  lastImportAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}